#! /bin/bash
#
# /etc/init.d/xmastree     
#
### BEGIN INIT INFO
# Provides: xmastree     
# Required-Start: $local_fs
# Should-Start: $local_fs
# Required-Stop:
# Should-Stop:
# Default-Start:  3 5
# Default-Stop:   0 1 2 6
# Short-Description: Merry Chrismas!     
# Description:  Stop and start xmastree daemon
### END INIT INFO

script=/usr/local/share/xmastree.py

case "$1" in
  start)
    echo "Starting server"
    # Start the daemon
    /usr/local/bin/zdaemon -C /etc/xmastree.conf start
    ;;
  stop)
    echo "Stopping server"
    # Stop the daemon
    /usr/local/bin/zdaemon -C /etc/xmastree.conf stop
    ;;
  restart)
    echo "Restarting server"
    /usr/local/bin/zdaemon -C /etc/xmastree.conf restart
    ;;
  *)
    # Refuse to do other stuff
    echo "Usage: /etc/init.d/xmastree {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
